language: android
jdk:
  - oraclejdk7
android:
  components:
    - platform-tools
    - tools
    - build-tools-22.0.0
    - android-22
    - extra-android-m2repository
before_script:
  - ./gradlew dependencies
script:
  - ./gradlew build
after_success:
  - ./gradlew jacocoTestReport coveralls