language: java
before_install:
  - wget http://dl.google.com/android/android-sdk_r22.3-linux.tgz
  - tar -zxf android-sdk_r22.3-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - TOOLS=$(android list sdk --no-ui | grep "Android SDK Platform-tools" | cut -d"-" -f1)
  - android update sdk --filter "$TOOLS" --no-ui --force
  - SDK=$(android list sdk --no-ui | grep ", API 14," | cut -d"-" -f1)
  - android update sdk --filter "$SDK" --no-ui --force
script:
   - mvn -fparent/pom.xml install