language: java
jdk:
  - oraclejdk7
before_install:
  - sudo apt-get install -qq libstdc++6:i386 lib32z1 expect
before_script:
  - ./gradlew dependencies
script:
  - ./gradlew build
after_success:
  - ./gradlew jacocoTestReport coveralls