language: android
jdk:
  - oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-26
    - sys-img-armeabi-v7a-android-19
before_script:
  - ./gradlew dependencies
script:
  - ./gradlew build
after_success:
  - ./gradlew jacocoTestReport coveralls
  - ./gradlew versioneye-update