language: android
jdk:
  - oraclejdk7
android:
  components:
    - build-tools-21.1.1
    - android-21
before_script:
  - chmod +x gradlew
script:
  - ./gradlew build
after_success:
  - ./gradlew jacocoTestReport coveralls
