language: android
jdk:
  - oraclejdk7
android:
  components:
    - build-tools-21.1.1
    - android-21
    - extra-android-m2repository
before_script:
  - ./gradlew dependencies
script:
  - ./gradlew build
after_success:
  - ./gradlew jacocoTestReport coveralls
