language: android
jdk:
  - oraclejdk7
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-android-m2repository
before_script:
  - ./gradlew dependencies
script:
  - ./gradlew build -i
after_success:
  - ./gradlew jacocoTestReport coveralls